name: Build Trigger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: ['main']
    tags: ['v*.*.*']
  pull_request:
    branches: ['main']

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build latest
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
          event-type: Build Latest
          client-payload: '{ "node": 18, "tag": "latest", "repo": "${{ github.repository }}" }'

      # - name: Trigger build Node 14
      #   uses: peter-evans/repository-dispatch@v2
      #   with:
      #     token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
      #     event-type: Build Node 14
      #     client-payload: '{ "node": 14, "tag": "node-v14", "repo": "${{ github.repository }}" }'

      # - name: Trigger build Node 16
      #   uses: peter-evans/repository-dispatch@v2
      #   with:
      #     token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
      #     event-type: Build Node 16
      #     client-payload: '{ "node": 16, "tag": "node-v16", "repo": "${{ github.repository }}" }'

      # - name: Trigger build Node 18
      #   uses: peter-evans/repository-dispatch@v2
      #   with:
      #     token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
      #     event-type: Build Node 18
      #     client-payload: '{ "node": 18, "tag": "node-v18", "repo": "${{ github.repository }}" }'

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 3
          keep_minimum_runs: 7
